---
title: "Kinetics_to_ggplot"
author: "Kdu Trufen"
date: "10 de setembro de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(readxl)
library(ggpmisc)
library(lubridate)
```

```{r}
# dados_cultivo_smase <- read_delim(file = "~/Documentos/dados_cultivo_smase.csv", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
dados_cultivo_smase <- read_delim(file = "~/Dropbox/kdutrufenr/dados_cultivo_smase.csv", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
dados_cultivo_smase <- dados_cultivo_smase %>% mutate(DO600nm = DO600nm %>% str_replace(pattern = ",", replacement = "."))
dados_cultivo_smase <- dados_cultivo_smase %>% mutate(DO600nm = DO600nm %>% as.numeric())
```

```{r}
my.formula <- dados_cultivo_smase$DO600nm ~ dados_cultivo_smase$Tempo
```

```{r}
# dados_cultivo_smase <- dados_cultivo_smase %>% mutate(Tempo = Tempo %>% paste0("2019-09-10", .) %>% as.POSIXct(tz = "GMT"))

# dados_cultivo_smase <- dados_cultivo_smase %>% mutate(Tempo = Tempo %>% lubridate::hms())

# dados_cultivo_smase <- dados_cultivo_smase %>% mutate(Tempo = Tempo %>% hour())

dados_cultivo_smase <- dados_cultivo_smase %>% mutate(Tempo = c(0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.25, 4.5, 4.75, 5, 5.25, 5.5, 6, 7, 8, 9, 10, 11, 12))
```


```{r, fig.width=10}
dados_cultivo_smase %>% ggplot(aes(x = Tempo, y = DO600nm)) + geom_point() + theme_bw() +  stat_poly_eq(formula = my.formula, eq.with.lhs = "italic(hat(y))~`=`~", aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), parse = TRUE) + geom_smooth(method = "lm") + labs(x = "Tempo (h)") + scale_x_continuous(breaks = seq(0:12), limits = c(0,12)) # + theme(axis.text.x = element_text(angle = 25)) #+ scale_x_date(date_breaks = "1 hour", date_labels = "%H:%M")
```

```{r}
dados_cultivo_smase %>% ggplot(aes(x = Tempo, y = DO600nm)) + geom_point() + theme_bw() +  geom_smooth(method = "loess")
```

